init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd Release
test: off
version: 0.0.1.{build}

# after build failure or success
on_finish:
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; $dest = [System.IO.Path]::Combine((Resolve-Path temp), "Log.Zip") ; [System.IO.Compression.ZipFile]::CreateFromDirectory("C:\OneNet\Log", $dest) ; Push-AppveyorArtifact $dest -FileName Log.Zip -DeploymentName to-publish

